- src/main/java/com/cryptomorin/xseries/XItemStack.java
```PotionData``` is now also serialized allowing vanilla potions to be serialized as well.
Please note that this is a very simple implementation, you may want to add this to XPotion and create a method similar to ```XPotion#parsePotionEffectFromString```. This PR is mainly to bring your attention to the topic, but, since I've already implemented it (possibly not in the best way), I thought why not share it.
> [XItemStack] Added support for vanilla potions in PotionMeta

- src/main/java/com/cryptomorin/xseries/XMaterial.java
Fern data id should be 2 instead of 1
> Fixed fern data id

- src/main/java/com/cryptomorin/xseries/XMaterial.java
Before on:
`XMaterial.matchXMaterial(1,0)`
`
Caused by: java.lang.NumberFormatException: For input string: "AT_ACACIA"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_252]
at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_252]
at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_252]
at com.cryptomorin.xseries.XMaterial.getId(XMaterial.java:1937) ~[?:?]
at com.cryptomorin.xseries.XMaterial.matchXMaterial(XMaterial.java:1665) ~[?:?]
`
After adding check whether the string contains dot:
`
Caused by: java.lang.NullPointerException: Unsupported material ID check: ANDESITE_SLAB (0)
at java.util.Objects.requireNonNull(Objects.java:228) ~[?:1.8.0_252]
at com.cryptomorin.xseries.XMaterial.getId(XMaterial.java:1940) ~[?:?]
at …
> Fix material parsing by id

- src/main/java/com/cryptomorin/xseries/particles/ParticleDisplay.java
- src/main/java/com/cryptomorin/xseries/particles/XParticle.java
Hey !
I recently used some XParticle methods and I found some weird behaviours. This is my first time pull request so I hope I'm not doing it wrong. I also added a `force` support on ParticleDisplay but I don't request it because if you haven't added it before, it's for a reason I guess.
ParticleDisplay :
Fixed `fromConfig` method. It was reading `rotation` var instead of `color` variable and the `size` value was set on the first color R with `color[0]` instead of `color[3]`.
XParticle :
Fixed `circle` method with 3 parameters.
Added a security to avoid infinite loops when rate is negative in `circle` and 'line' methods.
Added a `BukkitTask` return value in `atomic`, `explosionWave` and `spread` methods.
Fixed some typo "cirlce" in doc.
> [XPARTICLE] Fixed Xparticle circle and deserialization of ParticleDisplay

- src/main/java/com/cryptomorin/xseries/XBiome.java
- src/main/java/com/cryptomorin/xseries/XItemStack.java
- src/main/java/com/cryptomorin/xseries/XMaterial.java
Small one but I needed it.
Also, in later versions like 1.8 on deserialize **spawner.update(true);** does not work on itemstacks. You'll get an error saying something along the lines of you can only update a Block. I fixed it so it would work for 1.8-1.16 with the following:
**bsm.setBlockState(spawner); 
item.setItemMeta(meta);**
Just thought I would let you know, I'm aware other people use this for different things so might not work correctly for them in some cases so I didn't commit it.
I also added a fix in for fireworks, I had to use two array lists because for some reason the colors were not getting serialized correctly. This is the firework I used for testing:
```
firework:
'0':
type: BALL_LARGE
flicker: true
trail: false
base-colors:
- 59, 81, 26
- 65, 205, 52
fade-colors:
- 59, …
```
> [XItemStack] Spawner Serialize Support & Fixed Fireworks

- src/main/java/com/cryptomorin/xseries/XItemStack.java
The method **hasCustomModelData()** can't be used in <1.14 versions.
https://github.com/CryptoMorin/XSeries/blob/747ee8e2df3c267b5e41bd8170ada80b4e70c899/src/main/java/com/cryptomorin/xseries/XItemStack.java#L109
> [XItemStack] Fixed Unsupported getCustomModelData() for 1.14

- pom.xml
As @Im-Fran said in #116 , here it's a fix for Travis check.
According to maven doc (https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html) :
> Sets whether annotation processing is performed or not. Only applies to JDK 1.6+ If not set, both compilation and annotation processing are performed at the same time.
>
>Allowed values are:
>
>none - no annotation processing is performed.
>only - only annotation processing is done, no compilation.
Assuming Javax annotations are not build in the project.
> Pom.xml : No annotation processing is performed, set proc to none

- src/main/java/com/cryptomorin/xseries/particles/ParticleDisplay.java
- src/main/java/com/cryptomorin/xseries/particles/XParticle.java
There are two added features :
- Force support, like I did in #116.
- Support for BLOCK_CRACK, BLOCK_DUST, FALLING_DUST and ITEM_CRACK particles, customizable with data field and methods withBlock and withItem (#114). **In theory, the feature supports version 1.12 but I have not tested it.**
- It "fixed" issue #114 since it also allows particles like SPELL_MOB or SPELL_MOB_AMBIENT to use colors in the same way as REDSTONE does. When SPELL_MOB or 1.12 REDSTONE has count=0 (directionnal), the offset becomes the color and the speed becomes other thing, for REDSTONE it's size but for SPELL_MOB it's a mix of offset, speed and saturation color. In 1.13, REDSTONE changed to get other parameters, but not SPELL_MOB.
-> Tested in 1.16.5 with some recent Paper builds in java 15, but not in other …
> [ParticleDisplay] Force support and item/block datas

- src/main/java/com/cryptomorin/xseries/SkullUtils.java
In `SkullUtils#getSkinValue(ItemMeta)`, for some reason the `Field` instance is fetched every time the method is invoked. I presume this is not intended. This PR fixes it.
> [SkullUtils] Cache the reflections for the profile field getter

- src/main/java/com/cryptomorin/xseries/XItemStack.java
As mentioned [here](https://github.com/CryptoMorin/XSeries/issues/142), here's the PR introducing support for item serialization and deserialization to and from `Map`. The new code works just fine as far as I could test, both serialization methods (using `ConfigurationSection` and passing a `Map<String, Object>` directly) did produce the same output.
I got some NPEs along the process and did fix all of them in one commit, the exceptions I got can be seen below and validated as well. Feel free to modify anything, or ask for modifications.
- Added serialization and deserialization support for `Map<String, Object>`.
- Fixed #141 
- Fixed NPE when serializing items that had AttributeModifiers that weren't bound to a specific slot (so `slot` was `null`).
- Fixed NPE when deserializing items …
> Added serialization support for Maps

- src/main/java/com/cryptomorin/xseries/XMaterial.java
I've added a @ since 8.5.0 in the Javadoc for the `parseVersion(String version)` method, although I didn't bump the version number yet in the pom.xml.
Tested with the following version strings:
```
git-Spigot-3d850ec-809c399 (MC: 1.8)
git-Spigot-3d850ec-809c399 (MC: 1.8.2) 
git-Spigot-3d850ec-809c399 (MC: 1.9.4)
git-Spigot-3d850ec-809c399 (MC: 1.11.2)
git-Spigot-3d850ec-809c399 (MC: 1.12.2)
git-Spigot-3d850ec-809c399 (MC: 1.18 Pre-release 5)
git-Spigot-3d850ec-809c399 (MC: 1.18.2 Pre-release 5)
git-Spigot-3d850ec-809c399 (MC: 1.19)
```
> Improve parsing of Minecraft versions to resolve #145

- src/main/java/com/cryptomorin/xseries/particles/ParticleDisplay.java
Hello !
A small pull request to add compatibility for new `DUST_COLOR_TRANSITION` particle releaded in 1.17. The basic idea is to add three new numbers in the `float[]` data and get it back when we detect on spawn that we can add DustTransition instance.
I also fixed a small issue with the `edit` method when called from `fromConfig`. With a new ParticleDisplay instance, `display.data instanceof float[]` was always false so if the config had `size` and `color` values, 1 was the only reachable size even if the config set it to another value (because it was set to 1 and check if size is set is done after data instance float[]).
In deserialization, the second color for transition colors follows the idea of the first one : if `color` has 1 or 3 strings it's one full color (get with …
> [XParticle] Add DustTransition compatibility for ParticleDisplay

- src/main/java/com/cryptomorin/xseries/XMaterial.java
XMaterial#or(XMaterial alternateMaterial) is an utility method that changes this syntax: `XMaterial.NEW_MATERAL.isSupported() ? XMaterial.NEW_MATERIAL.parseMaterial() : XMaterial.ALTERNATE_OLD_MATERIAL.parseMaterial()` to this: `XMaterial.NEW_MATERIAL.or(XMaterial.ALTERNATE_OLD_MATERIAL.parseMaterial()`.
> Added an "or" method in XMaterial

- src/main/java/com/cryptomorin/xseries/SkullUtils.java
Fixed old version skull issue. Changed id.toString() to Bukkit.getOfflinePlayer(id).getName() because old version doesn't support uuid to owner skin. It only supports player name.
> Fix setting skull owner using UUID pre-1.13

- src/main/java/com/cryptomorin/xseries/XSound.java
I'm developing a plugin where a sound should be sent to all online players, which currently can be done using:
```java
for(Player online : Bukkit.getOnlinePlayers())
XSound.WHATEVER.playRepeatedly(Main.getInstance(), online, 1, 1, 5, 5);
```
But this is really bad because it creates a task per player, instead of 1 task for all players.
> Add support for playing a sound for multiple entities in a single task

- src/main/java/com/cryptomorin/xseries/XTag.java
Adds the newly added wood types (`CHERRY`, `BAMBOO`) so that
```java
XTag.SIGNS.isTagged(XMaterial.CHERRY_SIGN)
```
and
```java
XTag.SIGNS.isTagged(XMaterial.BAMBOO_SIGN)
```
both return `true`
* I'm not sure if the name [BAMBOO_LOGS](https://github.com/thomasmny/XSeries/blob/1a719b86fd5ccd9966d02b6d41d28aa0a38d14b2/src/main/java/com/cryptomorin/xseries/XTag.java#L99) is appropriate, because the `Material.BAMBOO_LOG` doesn't actually exists. I just called it that to match the other wood types.
* I also wasn't sure which tags to add the bamboo wood type to (sometimes only the cherry version was added). Would like to hear you feedback on what is missing
[XTag.HANGING_SINGS](https://github.com/CryptoMorin/XSeries/blob/52b085bd4934b064190a0e2dce96c05412914d22/src/main/java/com/cryptomorin/xser …
> [XTag] Add missing 1.20 wood types

- src/main/java/com/cryptomorin/xseries/particles/XParticle.java
This attempts to split all logic from particle tasks to be Runnable & BooleanSupplier, so that it can be used in other ways of scheduling tasks, like those new Folia's schedulers ([BukkitScheduler's deprecation note](https://jd.papermc.io/folia/1.19/org/bukkit/scheduler/BukkitScheduler.html)).
> Split runnables from task in XParticle

- src/main/java/com/cryptomorin/xseries/XTag.java
`INVENTORY_NOT_DISPLAYABLE` contained some materials that could be displayed and some materials that could not be displayed.
Along with the improvements to `INVENTORY_NOT_DISPLAYABLE`, I added `XMaterial.POTTED_TORCHFLOWER` to `FLOWER_POTS`, as well as three new tags (`WALL_TORCHES`, `FILLED_CAULDRONS` and `WALL_HANGING_SIGNS`) - all materials in these three tags cannot be displayed in an inventory. Also, I added `XTag#without(T...)` - this method returns a new XTag with all items that were included in the old one, except those specified as arguments. I'm not sure if this method could be useful outside the XTag class - but maybe it is and the method should be public instead?
For the changes regarding `INVENTORY_NOT_DISPLAYABLE` :
- I removed `XMaterial.CHORUS_PLANT` as it can be displayed …
> XTag - INVENTORY_NOT_DISPLAYABLE improvements 

- src/main/java/com/cryptomorin/xseries/XEntity.java
Whenever loading an Armor Stand entity with equipment, throws an error. By checking if the entity is a Mob instance prevents this error being thrown.
```log
java.lang.IllegalArgumentException: Cannot set drop chance for non-Mob entity
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar:?]
at org.bukkit.craftbukkit.v1_20_R1.inventory.CraftEntityEquipment.setDropChance(CraftEntityEquipment.java:260) ~[paper-1.20.1.jar:git-Paper-169]
at org.bukkit.craftbukkit.v1_20_R1.inventory.CraftEntityEquipment.setHelmetDropChance(CraftEntityEquipment.java:215) ~[paper-1.20.1.jar:git-Paper-169]
at com.cryptomorin.xseries.XEntity.edit(XEntity.java:213) ~[SnapSkyBlock-2.0.0-SNAPSHOT.jar:?]
at com.cryptomorin.xseries.XEntity.spawn(XEntity.java:121) …
```
> Error with equipment drop chance with armor stands

- src/main/java/com/cryptomorin/xseries/ReflectionUtils.java
- src/main/java/com/cryptomorin/xseries/SkullUtils.java
This PR fixes the issue mentioned in #226 as well as an NPE that occurs when trying to use SkullUtils.
I recognize the contributing guidelines say that changes shouldn't be made around the time a new minecraft version is released, but it's been over a week since 1.20.2 dropped, and I heard CryptoMorin is busy, so here's this. I've tried to keep the changes small and sensible, but if more changes are needed or if you'd like to just rewrite the changes from scratch, let me know.
The main change here is that the packet send method has been abstracted from `ServerGamePacketListenerImpl` to `ServerCommonPacketListenerImpl`. This change unfortunately occurred in its entirety across a "bug fix" version, so I've modified the `VersionHandler` class to accept patch versions as well, using …
> Fix issues for 1.20.2 (#226)

- src/main/java/com/cryptomorin/xseries/NMSExtras.java
- src/main/java/com/cryptomorin/xseries/NoteBlockMusic.java
- src/main/java/com/cryptomorin/xseries/ReflectionUtils.java
- src/main/java/com/cryptomorin/xseries/XBiome.java
- src/main/java/com/cryptomorin/xseries/XEnchantment.java
- src/main/java/com/cryptomorin/xseries/XEntity.java
- src/main/java/com/cryptomorin/xseries/XItemStack.java
- src/main/java/com/cryptomorin/xseries/XMaterial.java
- src/main/java/com/cryptomorin/xseries/XPotion.java
- src/main/java/com/cryptomorin/xseries/XSound.java
- src/main/java/com/cryptomorin/xseries/messages/ActionBar.java
- src/main/java/com/cryptomorin/xseries/messages/Titles.java
- src/main/java/com/cryptomorin/xseries/particles/XParticle.java
The Minecraft Fandom wiki has been forked to a new domain: minecraft.wiki. Learn more here: https://minecraft.wiki/w/Minecraft_Wiki:Moving_from_Fandom. This PR updates all URLs accordingly.
> Update Minecraft Wiki links to new domain

- src/main/java/com/cryptomorin/xseries/XItemStack.java
- Added support for Armor Trims
- Changed attribute modifier to use doubles instead of integers
- This has been a double ever since it was implemented in spigot 1.9
- Fixed unreachable code in XItemStack
- the following code would never reach when the server is on version 1.17 or higher, same goes for the other if checks below: https://github.com/CryptoMorin/XSeries/blob/6cbc1fc226f2eb0463700626e9f5db58f96ba339/src/main/java/com/cryptomorin/xseries/XItemStack.java#L779
- Same applies here: https://github.com/CryptoMorin/XSeries/blob/6cbc1fc226f2eb0463700626e9f5db58f96ba339/src/main/java/com/cryptomorin/xseries/XItemStack.java#L305
> Armor trims and unreachable code fix

- src/main/java/com/cryptomorin/xseries/XMaterial.java
Pre-flattening, matchXMaterial(ItemStack) matches splash potions to the SPLASH_POTION material type. Using parseItem() then results in a null item. This update will fix that.
> Fix splash potion material on old versions

- src/main/java/com/cryptomorin/xseries/NMSExtras.java
Fixed a WrongMethodTypeException thrown when the chest open animation method has been called.
Original error:
`
[13:24:00 WARN]: java.lang.invoke.WrongMethodTypeException: cannot convert MethodHandle(int,int,int)BlockPosition to (double,double,double)Object
[13:24:00 WARN]:        at java.base/java.lang.invoke.MethodHandle.asTypeUncached(MethodHandle.java:884)
[13:24:00 WARN]:        at java.base/java.lang.invoke.MethodHandle.asType(MethodHandle.java:869)
[13:24:00 WARN]:        at java.base/java.lang.invoke.Invokers.checkGenericType(Invokers.java:542)
[13:24:00 WARN]:        at ZombieSurvival-Revamped-1.0.0-all.jar//sv.file14.zs.shaded.xseries.xseries.NMSExtras.chest(NMSExtras.java:561)
[13:24:00 WARN]:        at ZombieSurvival-Revamped-1.0.0-all.jar//sv.file14.zombiesurvival.util.NMSUtil …
> Fix java.lang.invoke.WrongMethodTypeException:

- src/main/java/com/cryptomorin/xseries/XItemStack.java
```java
// Unbreakable item
ItemStack item = new ItemStack(Material.DIAMOND_SWORD);
ItemMeta meta = item.getItemMeta();
meta.setUnbreakable(true);
item.setItemMeta(meta);
ConfigurationSection config = new YamlConfiguration(); // empty config
// The item is no longer unbreakable
ItemStack sameItem = XItemStack.edit(item, config, Function.identity(), null);
```
> [XItemStack] XItemStack.edit() removes unbreakable state when not specified in the config

- src/main/java/com/cryptomorin/xseries/SkullUtils.java
> [SkullUtils] Fix SHA extraction from ValueType.TEXTURE_URL

- src/main/java/com/cryptomorin/xseries/particles/XParticle.java
Currently, in XParticle, `CRIT_MAGIC` [is said](https://github.com/CryptoMorin/XSeries/blob/d1bf398eba41bdf81857d1c297253bc2066505b7/src/main/java/com/cryptomorin/xseries/particles/XParticle.java#L33) to have been changed to `CRIT` in 1.20.5, but this doesn't seem to be correct based on [this diff](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/diff/src/main/java/org/bukkit/Particle.java?until=8a34e009148cc297bcc9eb5c250fc4f5b071c4a7). Based on that, it looks like `CRIT` is unchanged and `CRIT_MAGIC` has been changed to `ENCHANTED_HIT`. This PR fixes that so the `ENCHANTED_HIT`/`CRIT_MAGIC` particle works correctly on 1.20.4 and under.
> [XParticle] Correct `CRIT_MAGIC -> ENCHANTED_HIT`

- src/main/java/com/cryptomorin/xseries/particles/XParticle.java
In MC v1.18, the removed `BARRIER` and `LIGHT` particles in favor of the `BLOCK_MARKER` particle. More info here: https://minecraft.fandom.com/wiki/Particles
I feel that it is appropriate to have barrier and light as alternatives... though that is slightly opinionated since the new version of the particle requires block data to be sent.
> [XParticle] BARRIER, LIGHT -> BLOCK_MARKER (v1.18)

- src/main/java/com/cryptomorin/xseries/particles/XParticle.java
The `XParticle.BLOCK` enum is missing `BLOCK_CRACK` as an alt. `BLOCK_CRACK` was removed in 1.20.5 in favor of `BLOCK`
> [XParticle] add BLOCK_CRACK alt for BLOCK particle

- src/main/java/com/cryptomorin/xseries/reflection/XReflection.java
Using XSeries on Spigot 1.20(.0) results in this error in my plugin:
```
java.lang.ExceptionInInitializerError: null
at be.isach.ultracosmetics.shaded.xseries.XSkull.<clinit>(XSkull.java:138) ~[?:?]
at be.isach.ultracosmetics.util.ItemFactory.createSkull(ItemFactory.java:188) ~[?:?]
at be.isach.ultracosmetics.cosmetics.type.HatType.<init>(HatType.java:36) ~[?:?]
at be.isach.ultracosmetics.cosmetics.type.HatType.register(HatType.java:79) ~[?:?]
at be.isach.ultracosmetics.cosmetics.type.CosmeticType.registerAll(CosmeticType.java:99) ~[?:?]
at be.isach.ultracosmetics.UltraCosmetics.start(UltraCosmetics.java:311) ~[?:?]
at be.isach.ultracosmetics.UltraCosmetics.onEnable(UltraCosmetics.java:213) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) …
```
> [XReflection] Fix load error on versions with no patch

- src/main/java/com/cryptomorin/xseries/particles/ParticleDisplay.java
- src/main/java/com/cryptomorin/xseries/particles/Particles.java
**Description**
The note particles are a bit strange: they have 25 possible colors, which are indicated in the `dX`/`offsetX` parameter using a scaled value between 0 and 1 (and count must be 0 for this field to act as the color, otherwise it acts as an offset as usual.) This means that in order to spawn a specific color of note particle, I'm currently required to do something like this:
```java
display.withColor(new Color((noteColor / 24f) * 255, 0, 0)).withCount(0);
```
To make this more user-friendly, I've added a function `withNoteColor` that accepts the index of a note color to display, and does this calculation internally. (See [this](https://minecraft.wiki/w/Note_Block#Notes) wiki page for the possible colors).
There may be a better way to do this as well, I'm open to any feedback!
> [ParticleDisplay] Be generally more user-friendly

- src/main/java/com/cryptomorin/xseries/profiles/ProfilesCore.java
- src/main/java/com/cryptomorin/xseries/profiles/mojang/MojangAPI.java
- src/main/java/com/cryptomorin/xseries/profiles/objects/Profileable.java
This PR fixes #273 and some other minor bugs 
- Fix `MojangAPI.MOJANG_PROFILE_CACHE` condition
- Fix `ProfilesCore.UserCacheEntry_getProfile` not being accessible
- Fix remaps for `UserCache_profilesByUUID` and `UserCache_profilesByName`
- Remove unused reflected methods/fields
- Remove `Profileable#of(Player)`
> [XSkull] Legacy support

- src/main/java/com/cryptomorin/xseries/profiles/ProfilesCore.java
This pr fixes the mappings for the proxy. You can also confirm those mappings by https://mappings.cephx.dev/
> [XSkull] Support 1.20.1-1.20.5 proxy mappings

- src/main/java/com/cryptomorin/xseries/XItemStack.java
In the XItemStack docs, `Color` is defined as:
```
alias Color: for Text "red, green, blue" or "hex color"
```
However, XItemStack actually doesn't currently parse hex colors, only the comma-separated format is supported. This PR changes that, and now all of the following formats are supported:
- `r, g, b` (just like before)
- `#RRGGBB`
- `0xRRGGBB`
- decimal representation of `r << 16 | g << 8 | b`, as used in NBT
The hex representation is automatically converted to decimal by SnakeYAML (and then converted to a string), so that format and the decimal representation end up being handled the same in the code. The bare format `RRGGBB` is also supported if it can't be parsed as a base-10 number, but due to that restriction I don't recommend that.
> [XItemStack] Support hex colors

- src/main/java/com/cryptomorin/xseries/profiles/ProfilesCore.java
- src/main/java/com/cryptomorin/xseries/profiles/objects/ProfileContainer.java
Already sometime the ResolvableProfile exists (I think since 1.20.5) but now the GameProfile was replaced with the ResolvableProfile both in the CraftSkull & CraftMetaSkull classes. ResolvableProfile has a constructor accepts only a GameProfile to create a profile from a GameProfile and it also saves a gameProfile that is also created when it's not created with a game profile.
This pr adds two new method handles. One for creating a ResolvableProfile from a GameProfile and one to get the GameProfile back from a ResolvableProfile. I tested myself the changes for my plugins and with my changes it, Skulls (both Items & Blocks) working again on paper build 83.
This would also fix #298
_If I'm honest, I have zero clue how your abstraction over reflection even works and it looks really …
> [XSkull] Support v1.21.1b78+ ResolvableProfile

- src/main/java/com/cryptomorin/xseries/reflection/parser/ReflectionParser.java
Added Locale.ENGLISH for parse correct format.
An error occurred when try to parse PUBLIC in Turkish like PUBLİC
> [XReflection] - ReflectionParser usage of toUpperCase with Locale.ENGLISH

- src/main/java/com/cryptomorin/xseries/XMaterial.java
My project has some unit tests that run without starting a Bukkit server. This causes a NullPointerException in `XMaterial` when `Bukkit#getVersion` is called:
```
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.Server.getVersion()" because "org.bukkit.Bukkit.server" is null
at org.bukkit.Bukkit.getVersion(Bukkit.java:96)
at com.cryptomorin.xseries.XMaterial$Data.<clinit>(XMaterial.java:2317)
... 9 more
```
The tests don't actually call any `XMaterial` methods, but the class is initialized by an enum that looks something like this:
```java
VALUE_1("Some string", XMaterial.FURNACE),
VALUE_2("Some other string", XMaterial.CLOCK)
```
This PR aims to fix this by checking if `Bukkit#getServer` is `null` before calling `Bukkit#getVersion`
> [XMaterial] Fix NPE when no server is running (during unit tests)

- src/main/java/com/cryptomorin/xseries/XBiome.java
Fixes: #319
Fix a typo of setting maxHeight rather than the minHeight value in the World#getMinHeight check.
> [XBiome] Fix World#getMinHeight Check Setting Wrong Boolean

- src/main/java/com/cryptomorin/xseries/base/XRegistry.java
Having this data solves some minor problems for me. Being able to get the types is good when we want to wrap your generics with our own generics (if we do anything fancy). 
This PR just adds getters for the types already stored in `XRegistry`
> expose the form classes

- src/main/java/com/cryptomorin/xseries/XBlock.java
This should fix issues with attempting to access enum values from newer versions in 1.8, also false positives when using direct check (e.g. `XBlock.isMelon(null)`), as it would return true in 1.13+ because `BlockMaterial.MELON_BLOCK.material` is `null`.
> [XBlock] XBlock.isSimilar() Inconsistent pre-1.13 and post-1.13 Material enum checks

- core/src/main/java/com/cryptomorin/xseries/particles/ParticleDisplay.java
You would expect this code to produce a purple music note (according to the table [here](https://minecraft.wiki/w/Note_Block#Notes)):
```java
ParticleDisplay.of(XParticle.NOTE).withColor(12).spawn(loc);
```
But as it stands, you only get green, no matter what color you put in, due to `extra` defaulting to 0. For whatever reason, `extra` is multiplied by the first offset field (the place where the note color is typically stored) and so if either is 0, you only get green notes back. So the working code is this:
```java
ParticleDisplay.of(XParticle.NOTE).withColor(12).withExtra(1).spawn(loc);
```
That's definitely unexpected if you're not already used to the weirdness of the particle system, and perhaps even if you are. So, to resolve confusion, I've added a check to ensure `extra` is not 0 …
> [ParticleDisplay] Ensure 'extra' isn't 0 when setting note color

- core/src/main/java/com/cryptomorin/xseries/messages/Titles.java
`MinecraftConnection#sendPacket(Player, Object...)` expects a varargs list of individual packet objects, however currently `Titles.sendTitle(Player, int, int, int, MessageText, MessageText)` passes the packets list directly
Fixes #347
> [Titles] Fix ClassCastException caused by packet sending in newer versions

- core/src/main/java/com/cryptomorin/xseries/reflection/minecraft/MinecraftConnection.java
In 1.21.7 the obfuscated mapping for the `connection` field was changed from `f` to `g`
- [Previously (1.21.5)](https://mappings.dev/1.21.5/net/minecraft/server/level/ServerPlayer.html)
- [1.21.7](https://mappings.dev/1.21.7/net/minecraft/server/level/ServerPlayer.html)
> [XReflection] Update obfuscated mapping for 1.21.7 player connection

- pom.xml
This fixes JitPack builds and streamlines collaboration by automatically discovering and selecting a JDK toolchain with JDK version ${testJava} (or above). Explicit toolchain declaration in ~/.m2/toolchains.xml is no longer required for new collaborators, and the automatic selection also prevents tools like JitPack from mysteriously attempting to find a Java 6 path (https://github.com/CryptoMorin/XSeries/issues/329).
Successful JitPack build with this change: [https://jitpack.io/com/github/demengc/XSeries/ed391d7c76/build.log](https://jitpack.io/com/github/demengc/XSeries/ed391d7c76/build.log)
Additional information on automatic discovery of JDK toolchains (new in Apache maven-toolchains-plugin v3.2.0): https://github.com/apache/maven-toolchains-plugin/pull/14 / …
> JitPack Fix: Auto-discover JDK toolchain instead of requiring explicit toolchains.xml
