- XMaterial.java
- Refactored ImmutableMap to ImmutableEnumMap for performance improvements
- Used stream method reference over direct method invocation
- Replaced string utility implementation with one provided by a Spigot lib
- Removed condition redundancy
> Optimizations & Code Improvements

- src/main/java/com/cryptomorin/xseries/XItemStack.java
```power``` now gotten from the correct ```ConfigurationSection```.
Prevent NPE when firework has no effects.
> [XItemStack] Fixed deserialization bugs with FireworkMeta

- .travis.yml
It's from my project which is working*
https://github.com/portlek/SmartInventory/blob/master/.travis.yml
> Travis fix.

- src/main/java/com/cryptomorin/xseries/XItemStack.java
The color of potions is now also serialized.
> [XItemStack] Added support for colors in PotionMeta

- src/main/java/com/cryptomorin/xseries/XItemStack.java
Blue color is now gotten from the correct index
> [XItemStack] Fixed parseColor method

- src/main/java/com/cryptomorin/xseries/messages/ActionBar.java
+ Added Lambda in line 192
+ Added Clear ActionBar method (From line 195 to 214)
> Clear ActionBars and added Lambdas

- src/main/java/com/cryptomorin/xseries/XEnchantment.java
> Fix some EntityType-s are not available on low versions

- src/main/java/com/cryptomorin/xseries/XItemStack.java
Added Enchanted Book Stored Enchants Support!
Let me know if you would like anything changed, switching the path to enchants didn't work correctly for me and for whatever reason you want to load enchanted books with stored enchants and normal enchants it can be done this way.
I also added shulker box item support in one of the commits if you wanted to take a look.
> [XItemStack] Enchanted Book Stored Enchants & Shulker Box Support

- src/main/java/com/cryptomorin/xseries/XBiome.java
In the Nether update, they introduced the ability to have different biomes depending on the Y axies. This will fix setting the biome on 1.16+ versions
> [XBiome] Fixed issues for setting biomes on 1.16+

- src/main/java/com/cryptomorin/xseries/XItemStack.java
> [XItemStack] 1.8 Potion Support

- src/main/java/com/cryptomorin/xseries/NMSExtras.java
This PR fixes lighting for 1.16.x.
The PacketPlayOutSpawnEntityWeather was removed in 1.16.x, and now you have to use the PacketPlayOutSpawnEntity to spawn lighting.
> [NMSExtras] Fixed lightning for 1.16.x

- src/main/java/com/cryptomorin/xseries/XItemStack.java
- src/main/java/com/cryptomorin/xseries/XMaterial.java
Hello i added the BookMeta and the MapMeta into the project, also the SkullMeta serialization and deserialization was fixed for legacy versions. I also fixed some unsupported methods for legacy versions.
> [XItemStack] Major Changes - Map, Book & SpawnEgg Support

- src/main/java/com/cryptomorin/xseries/XBiome.java
Still need to do something about y starting at 0 but idk how to fix that so ill leave that to somone else
> since 1.17 world height can be higher than 256

- src/main/java/com/cryptomorin/xseries/XItemStack.java
Hello, i have added support for CompassMeta serialization and deserialization.
> [XItemStack] CompassMeta support

- src/main/java/com/cryptomorin/xseries/XItemStack.java
Hello Crypto, i have added the support for AxolotlBucketMeta :)
> [XItemStack] Support for AxolotlBucketMeta was added.

- src/main/java/com/cryptomorin/xseries/XBlock.java
* Should apply the modified `BlockData` to the `Block`
* Add `applyPhysics` to `setType`
> [XBlock] setBlockData & applyPhysics on setType

- src/main/java/com/cryptomorin/xseries/XBlock.java
> Replacing XMaterial.supports(13) with ISFLAT

- src/main/java/com/cryptomorin/xseries/XTag.java
> [XTag] Add mangrove wood type

- src/main/java/com/cryptomorin/xseries/NoteBlockMusic.java
- src/main/java/com/cryptomorin/xseries/XSound.java
Add an option to toggle either the whole world or only the player can hear the music
> playAtLocation option for NoteBlockMusic & Cloneable Record

- src/main/java/com/cryptomorin/xseries/particles/ParticleDisplay.java
Add a method to serialize ParticleDisplay to a ConfigurationSection.
Also add missing getters for particle, count & extra
> Serialization for ParticleDisplay

- src/main/java/com/cryptomorin/xseries/XBiome.java
- src/main/java/com/cryptomorin/xseries/XEnchantment.java
- src/main/java/com/cryptomorin/xseries/XPotion.java
- src/main/java/com/cryptomorin/xseries/XSound.java
This PR resolves #207.
I've added #or() to XSound, XPotion, XEnchantment and to XBiome.
> Added or() methods to XSeries Utilities (#207)

- src/main/java/com/cryptomorin/xseries/XItemStack.java
> Fixed return value of CreatureSpawner#getSpawnedType is null

- src/main/java/com/cryptomorin/xseries/particles/XParticle.java
Goes along with #260... Basically, it seems like there are a bunch of mistakes in XParticle, so I looked at the [spigot commit](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/diff/src/main/java/org/bukkit/Particle.java?until=8a34e009148cc297bcc9eb5c250fc4f5b071c4a7) that made all the changes and fixed the XParticle mistakes.
I also added some docs, and did some minor reorganization.
> [XParticle] v1.20.5 Renaming fix

- src/main/java/com/cryptomorin/xseries/XSound.java
To improve compatibility with projects that use this method a ton.
> [XSound] Re-add play methods with volume and pitch for convenience

- src/main/java/com/cryptomorin/xseries/XEntity.java
I think this is useful for more cases than just as a private method for XEntity#edit
> public XEntity#editBossBar

- jitpack.yml
This is for those who want to use dev-builds for quick testing and delivering.
It's still recommended to use the release build.
> Add Jitpack settings

- jitpack.yml
- src/main/java/com/cryptomorin/xseries/XTag.java
Updates XTag with all 1.21.4 pale oak items
> XTag added pale oak

- core/src/main/java/com/cryptomorin/xseries/particles/Particles.java
Image rotation is wrong in some facing
> [Particles] Fix displayRenderedImage() rotation
